FROM ubuntu:latest

#To install without any interactive dialogue
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
# Installing Nautilus File Manager
RUN apt-get install nautilus -y

CMD ["nautilus"]
